### ISSUE TITLE
MwSt. für USt.-befreite Kundengruppe

### ISSUE THREAD

**Issue by ghost** [Magenerds/GermanLaw#11]
Guten Tag,
wir betreiben einen Magento 2 Onlineshop mit insgesammt 3 Kundengruppen.

1. Angemeldete Kunden
2. Angemeldete Firmen ( Firmensitz in Deutschland )
3. Angemeldete Firmen ( Firmensitz außerhalb Deutschlands )

Kundengruppe 3 kauft sämtliche Produkte netto ein. Sprich ohne MwSt. - Leider scheint das Modul den Prozentsatz direkt vom Produkt zu bekommen ohne eine Überprüfung der Kundengruppe zu machen um in diesem zu schauen ob er überhaupt MwSt. zahlen muss.

DIe Preise werden innerhalb Magento perfekt und richtig angezeigt, einzig und allein der Prozentsatz in "Inkl. 19% MwSt., zzgl. Versand" wird falsch wiedergegeben.

Wäre super wenn sich jemand diesem Problem annehmen könnte.

Mit freundlichen Grüßen, 
Marcel

**Comment by ghost** [comment]
Hierzu irgendetwas neues ?

**Comment by sydekumf** [comment]
Thanks for opening this ticket. It is fixed with this release: https://github.com/Magenerds/GermanLaw/releases/tag/1.0.13
