### ISSUE TITLE
Module überschreibt bereits existierende Seiten

### ISSUE THREAD

**Issue by Gamewalker** [Magenerds/GermanLaw#12]
Bitte checken ob eine CMS Seite existiert bevor diese mit dem Dummy Text angelegt wird. Meine fertiges Impressum und AGB sind nun leider weg :(

**Comment by sydekumf** [comment]
Hallo,

generell gehen wir bei der Installation von Extensions davon aus, dass diese in einem frischen Magentoshop installiert werden bzw. vorab ein Backup gemacht wird, sollten sensible Daten verloren gehen können. Die entsprechende Doku liefert übrigens Informationen über das Modul, und was es installiert: http://doc.magenerds.com/germanlaw/

Viele Grüße,
Florian
