### ISSUE TITLE
cms pages during installation are not present anymore

### ISSUE THREAD

**Issue by chequille** [Magenerds/GermanLaw#20]
Hi,
the 5 cms pages are not generated anymore under Magento 2.2.1

Already know error?

BR
Jürgen

**Comment by sydekumf** [comment]
Hi,
we installed the module in a fresh CE 2.2.1 and could not reproduce the problem. What did you do exactly? What steps?

Thanks!

**Comment by chequille** [comment]
Hi,
I downloaded the master.zip file, unpacked it and uploaded everything to the app/code/Magenerds/GermanLaw directory on my webserver.
Afterwards a did run bin/magento setup:ugrade
Thats all.
Everything seems to be OK, except of the not generated 5 cms pages Widerruf, Versand etc.
BR
Jürgen

**Comment by sydekumf** [comment]
Okay, do you see any logs in `var/log` directory? Otherwise I don't know what can be the cause, because we could not reproduce that issue.

**Comment by chequille** [comment]
Hi Florian,
unfortunately no!

Never mind, I do not wonder about such things with Magento2. There are too much dependencies regarding Webserver, used PHP version and and and ....
Magento2 is a developer system, far away from a system which can be used by normal users !?!?!?!?!

The other stuff of your extension is working and it is no problem to add the sites manually. Therefore I close this issue.
Thanks for your help.
BR
Jürgen
