### ISSUE TITLE
error in frontend when inline translation for frontend is activated

### ISSUE THREAD

**Issue by ChrisFM** [Magenerds/GermanLaw#4]
the following error occures, when frontend inline translation is switched on:

1 exception(s):
Exception #0 (Exception): Warning: sprintf(): Too few arguments in /home/---/public_html/app/code/Magenerds/GermanLaw/Block/AfterPrice.php on line 136

Exception #0 (Exception): Warning: sprintf(): Too few arguments in /home/___/public_html/app/code/Magenerds/GermanLaw/Block/AfterPrice.php on line 136
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'sprintf(): Too ...', '/home/---..', 136, Array)
#1 /home/___/public_html/app/code/Magenerds/GermanLaw/Block/AfterPrice.php(136): sprintf('{{{Inkl. %s MwS...', '19%')

could you confim this Bug?

**Comment by sydekumf** [comment]
Thanks for reporting. It got fixed in https://github.com/Magenerds/GermanLaw/releases/tag/1.0.9 :-)
