### ISSUE TITLE
Error filtering template: Element with ID 'after_price' already exists.

### ISSUE THREAD

**Issue by Tibi38** [Magenerds/GermanLaw#5]
Hallo,
I had installed 1.0.3 and have following Problem:
I use m2 with 3 Shops: hu, en and german.
Now I tried to install german law Extension.
Installation successful.
Then I disable the Extension in SHOP->Konfiguration in General and then I activate it in de-shop.
In de everything is shown right, only in the other Shops, the error:
Error filtering template: Element with ID 'after_price' already exists.
Appears.
I want to ask you for help.
Best regards Thomas

**Comment by sydekumf** [comment]
I just fixed it in version 1.0.6 :-)
