### ISSUE TITLE
Ink MwSt., zzgl Versand is shown twice on product page

### ISSUE THREAD

**Issue by NN01010101** [Magenerds/GermanLaw#8]
Screenshoot:
![bildschirmfoto 2017-02-17 um 07 17 07](https://cloud.githubusercontent.com/assets/10622794/23054595/27520284-f4e1-11e6-9ce4-8ba64957ec57.png)

Html Code:
![bildschirmfoto 2017-02-17 um 07 19 01](https://cloud.githubusercontent.com/assets/10622794/23054625/6c6f62c6-f4e1-11e6-8626-3703e1b9fee8.png)

**Comment by sydekumf** [comment]
Hi, which version of the extension are you using?
There is already a fix for that: https://github.com/Magenerds/GermanLaw/commit/65127c86acf9686e829dc5c19b60573fd32f3ff8
It was included in 1.0.2, but there are even newer release: https://github.com/Magenerds/GermanLaw/releases

**Comment by NN01010101** [comment]
Hi sorry, my bed. I had installed old version 1.0.1. Last version did the job. 
Thank you very much!
